# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1

/gun/particle e-
/gun/energy 6 MeV
/tracking/verbose 2

/B5/detector/targetAngle 64 deg
#
/run/beamOn 1
